using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class SceneChangeButton : MonoBehaviour
{
    private bool firstPush = false;
    string objname = null;

    private void Start()
    {
        // ‘JˆÚæ‚ğw’è‚·‚é‚½‚ßAƒ{ƒ^ƒ“–¼‚ğæ“¾‚·‚é
        objname = this.name;
    }

    private void Update()
    {
    }

    public void ButtonClicked()
    {
        PressStart();
    }
    public void PressStart()
    {
        // ‰æ–Ê‘JˆÚˆ—‚Ì‘½d‹N“®–h~
        if (!firstPush)
        {
            FadeManager.Instance.LoadScene(objname, 1.0f);
            firstPush = true;
        }
    }
}